version: '3.6'
services:
  server:
    image: redash/redash:8.0.2.b37747
    command: server
    depends_on:
      - redash_postgres
      - redash_redis
    ports:
      - "5001:5000"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 3s
        order: start-first
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redash_redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres:123456@redash_postgres/postgres"
      REDASH_COOKIE_SECRET: "123456"
      REDASH_WEB_WORKERS: 4
      #邮箱 
      REDASH_MAIL_SERVER: "smtp.exmail.qq.com"
      REDASH_MAIL_PORT: 465
      REDASH_MAIL_USE_TLS: "false"
      REDASH_MAIL_USE_SSL: "true"
      REDASH_MAIL_USERNAME: "no-reply@yoursite.com"
      REDASH_MAIL_PASSWORD: "111111"
      REDASH_MAIL_DEFAULT_SENDER: "no-reply@yoursite.com"
      REDASH_HOST: "http://redash.mysite.com"
  worker:
    image: redash/redash:8.0.2.b37747
    command: scheduler
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 3s
        order: start-first
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redash_redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres:123456@redash_postgres/postgres"
      QUEUES: "queries,scheduled_queries,celery"
      REDASH_COOKIE_SECRET: "123456"
      WORKERS_COUNT: 2
      #邮箱 
      REDASH_MAIL_SERVER: "smtp.exmail.qq.com"
      REDASH_MAIL_PORT: 465
      REDASH_MAIL_USE_TLS: "false"
      REDASH_MAIL_USE_SSL: "true"
      REDASH_MAIL_USERNAME: "no-reply@yoursite.com"
      REDASH_MAIL_PASSWORD: "111111"
      REDASH_MAIL_DEFAULT_SENDER: "no-reply@yoursite.com"
      REDASH_HOST: "http://redash.mysite.com"
  redash_redis:
    image: redis:5.0-alpine
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 3s
        order: start-first
  redash_postgres:
    image: postgres:9.6-alpine
    volumes:
      - ~/postgres/data:/var/lib/postgresql/data/
    environment:
      # POSTGRES_DB: postgres
      # POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123456"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 3s
        order: start-first
volumes:
  postgres-data:
    name: postgres-data
networks:
  default_overlay:
    external: true