version: "3"
services:
  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./redash_nginx.conf:/etc/nginx/conf.d/redash_nginx.conf
