version: '2'
services:
    mysql:
        network_mode: "bridge"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_USER=brian
            - MYSQL_PASS=123456
        image: "mysql/mysql-server:8.0"
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "./db:/var/lib/mysql"
            # - "./conf/my.cnf:/etc/my.cnf"
            # - "./init:/docker-entrypoint-initdb.d/"
        ports:
            - "3306:3306"
