version: '3.2'
services:
  zookeeper:
    image: zookeeper:3.7.0
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: bitnami/kafka:3.1.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    restart: always
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.21.3:9092
      - KAFKA_CFG_LISTENERS=CLIENT://0.0.0.0:9092,EXTERNAL://192.168.21.3:9093
      - KAFKA_ZOOKEEPER_PROTOCOL=zookeeper
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
 